kafka:
  brokers: localhost:9092
  group:
    id: zhisheng
  zookeeper:
    connect: localhost:2181
stream:
  parallelism: 1
  checkpoint:
    interval: 1000
    enable: false
# JDBC
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.71:54321/zbjsdb
    username: zbjs_readwrite
    password: zbjs_readwrite
